### ISSUE TITLE
Micronesia updated geo coordinates

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog#108] opened 2017-08-07 08:43 UTC
Sonsorol -> 5.328596, 132.221282
Tobian -> 3.004528, 131.171295

I'm going over some dots for Micronesia anyway, might come more. If so, I'll post them in this thread

**Comment by d97hah** [comment] 2017-08-07 13:21
Thanks I've update them for next version

2017-08-07 10:43 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment] 2017-08-08 03:49
Chamorro -> 13.438011, 144.744740 (to make it more distinct from Carolinian, which originates from the caroline islands but is now spoken in northern Marianas & Tapanag)

**Comment by HedvigS** [comment] 2017-08-08 03:58
Mortlockese - > 5.507350, 153.710778
Chuukese - > 7.346993, 151.598607

(these are basically all cases where it seems like the dot for the language has been placed just in the middle of the nation state, I'm just pulling them apart more to their actual respective island/islands)

**Comment by HedvigS** [comment] 2017-08-08 04:11
Pollapese - > 7.638875, 149.428723

**Comment by d97hah** [comment] 2017-08-08 15:18
Thanks all so adjusted for next version

2017-08-08 6:11 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HughP** [comment] 2017-10-17 21:24
Um, what was the reason for the error? 
What was the datum and the epoch of the source and what is the datum and epoch of the new contribution? see: http://hugh.thejourneyler.org/2011/language-documentation-and-the-datum/ and https://en.wikipedia.org/w/index.php?title=Datum_(geodesy)&oldid=422063702 and https://en.wikipedia.org/wiki/World_Geodetic_System#A_new_World_Geodetic_System:_WGS_84

It is completely possible that viewers are using WGS84 and the data is not designed for that datum.

**Comment by HedvigS** [comment] 2017-10-17 23:24
@HughP I suspect it's wrong data in Ethnologue and/or something that went wrong when @d97hah tried to automatically replace them onto landmasses in some way by finding the central point in the language or nation state polygon that is on land.

I didn't really investigate why, I just noticed it and submitted better coordinates that I know make sense because of the names of islands or because of knowledge I've acquired about Micronesian languages from reading literature and/or talking to Andy Pawley :).

It may have to do with the datum, but then wouldn't more dots be systematically wrong? These were just a few coordinates that were misplaced, and they weren't misplaced in a systematic way.

**Comment by HughP** [comment] 2017-10-19 22:40
Well, Ethnologue maps made use of a data set call populated places provided by GMI. GMI chose to round their coordinates,  and I don't think they were on the WGS84 datum, but I can't remember exactly the GMI datum. I known that when I was working in Mexico some of the coastal villages would appear in the ocean. It was an issue with the populated places data set. I would find it curious that glottolog would import and use point data from Ethnologue. With the heavy emphasis of citations in Glottalog, I am curious to know where the data for points Glottalog uses comes from.... 

I think I wrote about it here: http://hugh.thejourneyler.org/2012/some-current-challenges-in-using-gis-information-in-the-sil-international-corporate-knowledge-system/

**Comment by HedvigS** [comment] 2017-10-20 03:20
As far as I know, some coordinates have been imported but they've been subject to change and updates as people file issues (like this one), merges with other datasets suggests changes or when they are obviously wrong (for example in water). I can't see that Glottolog cites the source for each coordinate, like they do for trees and classification.

**Comment by xflr6** [comment] 2017-11-22 09:40
Most of the coordinate here where changed again by 373c53a77bd56f2834bd80932d8c89174de2f3bb.
@d97hah can you verify that the later changes are as intended and not regressions?

Sonsorol fixed in 5931597f2d8bb6349661678a269f86fb983793fc, possible regression in 373c53a77bd56f2834bd80932d8c89174de2f3bb:
https://github.com/clld/glottolog/blame/master/languoids/tree/aust1307/mala1545/cent2237/east2712/ocea1241/micr1243/micr1244/cent2276/west2844/pona1247/truk1243/west2855/sons1245/sons1242/md.ini

Tobian fixed in 6f60d9e5533b2ef04a0d4a057036cb75ddc017b6, possible regression in 373c53a77bd56f2834bd80932d8c89174de2f3bb:
https://github.com/clld/glottolog/blame/master/languoids/tree/aust1307/mala1545/cent2237/east2712/ocea1241/micr1243/micr1244/cent2276/west2844/pona1247/truk1243/west2855/sons1245/tobi1238/md.ini

Chamorro fixed in 00bfccee43fbc7f4f630939ae63933343d9e7c89, possible regression in 373c53a77bd56f2834bd80932d8c89174de2f3bb:
https://github.com/clld/glottolog/blame/master/languoids/tree/aust1307/mala1545/cham1312/md.ini

Mortlockese fixed in cc298d121dd7dada57707fbd1c6ad57765d13f2c, possible regression in 373c53a77bd56f2834bd80932d8c89174de2f3b:
https://github.com/clld/glottolog/blame/master/languoids/tree/aust1307/mala1545/cent2237/east2712/ocea1241/micr1243/micr1244/cent2276/west2844/pona1247/truk1243/nucl1749/cent2290/east2764/mort1238/mort1237/md.ini

Chuukese fixed in 98e1acc82615ed610e501180766076fb752cc7ae, possible regression in 373c53a77bd56f2834bd80932d8c89174de2f3bb:
https://github.com/clld/glottolog/blame/master/languoids/tree/aust1307/mala1545/cent2237/east2712/ocea1241/micr1243/micr1244/cent2276/west2844/pona1247/truk1243/nucl1749/cent2290/east2764/mort1238/chuu1238/md.ini

Pollapese fixed in 6176155c8c6fcb33de630ece3f71b1f0b11c5445:
https://github.com/clld/glottolog/blame/master/languoids/tree/aust1307/mala1545/cent2237/east2712/ocea1241/micr1243/micr1244/cent2276/west2844/pona1247/truk1243/nucl1749/cent2290/east2764/pulu1244/poll1238/md.ini

**Comment by d97hah** [comment] 2017-11-22 12:55
Good catch, see new PR

2017-11-22 10:40 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Closed** 2018-07-25 09:16 UTC
